//! #245: the generated-header sniff (`[ingest.code] skip_generated_header`)
//! must apply to code files only. A Markdown note whose first lines say
//! "DO NOT EDIT" is a note, not generated code, and must be indexed.

use kebab_config::Config;
use kebab_core::SourceScope;
use kebab_source_fs::FsSourceConnector;

#[test]
fn generated_marker_skips_code_but_not_markdown() {
    let tmp = tempfile::tempdir().unwrap();
    std::fs::write(
        tmp.path().join("note.md"),
        "DO NOT EDIT this list by hand, it is regenerated by the weekly job.\n\n# Weekly\n",
    )
    .unwrap();
    std::fs::write(tmp.path().join("gen.rs"), "// @generated by tonic-build\nfn x() {}\n").unwrap();
    std::fs::write(tmp.path().join("plain.md"), "# Plain\n").unwrap();

    let mut cfg = Config::defaults();
    cfg.workspace.root = Some(tmp.path().to_string_lossy().into_owned());
    cfg.workspace.exclude.clear();
    cfg.ingest.code.skip_generated_header = true;

    let conn = FsSourceConnector::new(&cfg).expect("connector init");
    let (assets, skips) = conn
        .scan_with_skips(&SourceScope::default())
        .expect("scan");

    let names: Vec<String> = assets
        .iter()
        .map(|a| a.workspace_path.0.clone())
        .collect();
    assert!(names.iter().any(|n| n.ends_with("note.md")), "note.md must be indexed: {names:?}");
    assert!(names.iter().any(|n| n.ends_with("plain.md")), "plain.md must be indexed: {names:?}");
    assert!(!names.iter().any(|n| n.ends_with("gen.rs")), "gen.rs must be skipped: {names:?}");

    assert_eq!(skips.skipped_generated, 1, "exactly the .rs file counts as generated");
    assert!(
        skips.skip_examples.generated.iter().any(|p| p.ends_with("gen.rs")),
        "skip sample should name gen.rs: {:?}",
        skips.skip_examples.generated
    );
}
